### ISSUE TITLE
Are you using this for anything?

### ISSUE THREAD

**Issue by briangonzalez** [wtfaremyinitials/osa-imessage#10]

**Comment by wtfaremyinitials** [comment]
Yes! I use it for a few small scripts I use personally (auto reply, group chat moderation, etc)

In addition I have been playing around with a command line iMessage client. It's still very rough around the edges so I have yet to push that to GitHub.

**Comment by briangonzalez** [comment]
Neat! I would love to help. I would also be interested in creating an alfred integration.
