### ISSUE TITLE
Move to async/await and node-sqlite

### ISSUE THREAD

**Issue by briangonzalez** [wtfaremyinitials/osa-imessage#12]
[node-sqlite](https://github.com/kriasoft/node-sqlite) is a promise-ified wrapper over sqlite3.

Would you be ok with me refactoring osa-imessage to use async/await and node-sqlite?  I think it would clean up the code quite a bit. I am also hoping to add in a mock sqlite db and use it to power a small unit testing suite.

Thoughts?

**Comment by wtfaremyinitials** [comment]
Sure, that would be fantastic! Please be sure to keep the refactor and feature additions in separate commits.
