### ISSUE TITLE
Unable to send text

### ISSUE THREAD

**Issue by svenyonson** [wtfaremyinitials/osa-imessage#20]
# using the example from the readme in file:

    const imessage = require('osa-imessage');
    imessage.send('+<mycellnumber>', 'Hello World!')

# fails with this error:
svens-mbp:osa-test svenyonson$ node test.js

    (node:21987) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 
    1): Error: Command failed: /usr/bin/osascript -l JavaScript
    445:509: execution error: Error on line 19: Error: no thread with handle '+<mycellnumber>' (-2700)

    (node:21987) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In 
    the future, promise rejections that are not handled will terminate the Node.js process with a 
    non-zero exit code.

**Comment by KarinaFernandez** [comment]
Hi @svenyonson ! I tried to send a message without success too, but I think that my problem is that I am executing it at anywhere. 
Could you please tell me where are you running the command `imessage.send('+<mycellnumber>', 'Hello World!')`?

Thanks in advance!

**Comment by wtfaremyinitials** [comment]
Have you send an iMessage to that phone number using your Mac before?

**Comment by svenyonson** [comment]
I'm sending it from my Mac, to my phone, in a simple Node.js script. Tryed the code interactively and from a .js file.

**Comment by wtfaremyinitials** [comment]
Try sending a message to your phone via your Mac with the built in Messages app before trying `osa-imessage`

**Comment by svenyonson** [comment]
Yes. Works fine.

**Comment by wtfaremyinitials** [comment]
Okay, now try `osa-imessage`

**Comment by svenyonson** [comment]
Same error. 

I literally copied the osa-imessage project folder (repo), ran npm install, then added a script called test.js.

then I execute: node test.js



$ cat test.js
const imessage = require('osa-imessage');

imessage.send('+3035206372', 'Hello World!')
 






$ node test.js
(node:23350) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Command failed: /usr/bin/osascript -l JavaScript
445:509: execution error: Error on line 19: Error: no thread with handle '+3035206372' (-2700)

(node:23350) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by wtfaremyinitials** [comment]
Try including the country code on the phone number. (`+13035206372`)

**Comment by svenyonson** [comment]
That worked!

Thanks a bunch for your time and effort.

**Comment by wtfaremyinitials** [comment]
Happy to help. Cheers

**Comment by enzotrompeneers** [comment]
I can only send a message when I interacted with the phone number before by Imessage mac/iphone. It doesn't send if there is no chat active with that person. Any ideas on that?
