### ISSUE TITLE
Problems installing

### ISSUE THREAD

**Issue by KarinaFernandez** [wtfaremyinitials/osa-imessage#21]
Hi! Once that I installed it I get this errors:

![screen shot 2017-12-21 at 10 14 54](https://user-images.githubusercontent.com/11321277/34257261-e6aa2394-e637-11e7-8395-3ab58b362c05.png)

Could you help me?

**Comment by wtfaremyinitials** [comment]
Those are just warnings that appear because you haven't created a [`package.json` file](https://docs.npmjs.com/getting-started/using-a-package.json) yet. `osa-imessage` should work just fine!
