### ISSUE TITLE
What is the `Application` function?

### ISSUE THREAD

**Issue by jbis9051** [wtfaremyinitials/osa-imessage#28]
This is quite possibly a dumb question, but it seems that everything boils down to the `Application` function [here](https://github.com/wtfaremyinitials/osa-imessage/blob/master/index.js#L79). 

My question is, where is that function defined? Where is it documented? Is it built it? 

I can't find anything on it, but that could be because I don't know where to look.

**Comment by jbis9051** [comment]
Oh. It's JavaScript Apple Script.

**Comment by wtfaremyinitials** [comment]
Correct. Also worth mentioning my module [osa2](https://www.npmjs.com/package/osa2) is used to bridge between nodejs and Apple's Javascript Automation runtime. @jbis9051

**Comment by jbis9051** [comment]
@wtfaremyinitials Yep, saw that. That is a very cool project, could be used for so much! Thanks for the help.
